### ISSUE TITLE
CSS class 참조에 대한 내용

### ISSUE THREAD

**Issue by 201411108** [201411108/global-navigation-bar#7]
`className='aside-menu mobile'`과 같이 적용한 경우 기존 프로젝트에서는 `aside-menu`와 `mobile`을 별도의 클래스 이름으로 css에서 처리했었는데 미디어 쿼리 내에서 이를 예하 클래스 이름으로 사용함.

### 예상한 사용법
```css
.desktop {
      display: none;
 }
 .desktop {
     display: none;
 }
```

### 실제 사용 구문
``` css
.aside-item.desktop {
    display: none;
}
.aside-btn.desktop {
    display: none;
}
```

이에 대한 이유 확인해보기
